approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: true
reviewers:
  -
    name: default
    required: 1
    members:
      - joemelt101
    conditions:
      branches:
        - premaster
        - master
